apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: prod-

patches:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

bases:
  - ../../base


