kind: ConfigMap
apiVersion: v1
metadata:
  name: api-nginx.conf
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 100000;
    events {
      worker_connections 8192;
      use epoll;
      multi_accept on;
    }
    http {
      access_log /dev/stdout;
      error_log /dev/stdout;

      include mime.types;

      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html/app/public;
        index index.php;
        server_name _;

        location / {
          try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
