apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource 
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
